// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPwUCQLgM-FeG6mTcAZjcI_I-SExnOpsg',
    appId: '1:751171755695:web:a9b4cb9c55f5831d167e5a',
    messagingSenderId: '751171755695',
    projectId: 'anirate-12615',
    authDomain: 'anirate-12615.firebaseapp.com',
    storageBucket: 'anirate-12615.appspot.com',
    measurementId: 'G-DM6YRYWB7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxYK1ac-19Gju4vvmTBJUGey4i-X8DjXQ',
    appId: '1:751171755695:android:05fd50b7baea3d62167e5a',
    messagingSenderId: '751171755695',
    projectId: 'anirate-12615',
    storageBucket: 'anirate-12615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbaJ-g_qBcZwIkmFU7iay4NGa5GVgpTi8',
    appId: '1:751171755695:ios:5e4318d5776a44c7167e5a',
    messagingSenderId: '751171755695',
    projectId: 'anirate-12615',
    storageBucket: 'anirate-12615.appspot.com',
    iosBundleId: 'com.example.aniRate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbaJ-g_qBcZwIkmFU7iay4NGa5GVgpTi8',
    appId: '1:751171755695:ios:5e4318d5776a44c7167e5a',
    messagingSenderId: '751171755695',
    projectId: 'anirate-12615',
    storageBucket: 'anirate-12615.appspot.com',
    iosBundleId: 'com.example.aniRate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPwUCQLgM-FeG6mTcAZjcI_I-SExnOpsg',
    appId: '1:751171755695:web:7de38025023351d9167e5a',
    messagingSenderId: '751171755695',
    projectId: 'anirate-12615',
    authDomain: 'anirate-12615.firebaseapp.com',
    storageBucket: 'anirate-12615.appspot.com',
    measurementId: 'G-N59EKSJR4J',
  );
}
